spring.application.name=my-springboot-platform

spring.datasource.url=jdbc:mysql://localhost/techdispatch
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
